import { 
  Users, Target, Bot, MessageCircle, Calendar, BarChart3, Bell, Brain, 
  ClipboardCheck, Headphones, DollarSign, ShoppingCart, Heart, Pill, 
  Stethoscope, Scale, Camera, Wrench, Building2, Truck, Package, Home,
  GraduationCap, Hammer, Smile, LucideIcon
} from "lucide-react";
import { NicheConfig } from "./NicheLandingPage";

export const nicheConfigs: Record<string, NicheConfig> = {
  dentista: {
    slug: "dentista",
    title: "CRM para Dentistas",
    subtitle: "Especializado para Odontologia",
    heroTitle: "O CRM que dentistas",
    heroHighlight: "realmente precisam",
    heroDescription: "Gerencie seus pacientes, agendamentos e follow-ups automaticamente. Robôs IA que confirmam consultas, lembram de retornos e qualificam novos pacientes pelo WhatsApp.",
    painPoints: [
      "Pacientes que esquecem de confirmar consultas",
      "Follow-up manual de tratamentos em andamento",
      "Perder pacientes por falta de contato pós-consulta",
      "Não saber quais pacientes precisam de retorno",
    ],
    benefits: [
      { icon: Calendar, title: "Confirmação Automática", description: "Robô confirma consultas 24h antes automaticamente" },
      { icon: Bell, title: "Lembrete de Retorno", description: "Avisa pacientes quando é hora de voltar" },
      { icon: Bot, title: "Qualificação de Leads", description: "IA qualifica novos pacientes pelo WhatsApp" },
      { icon: MessageCircle, title: "Follow-up Pós-Consulta", description: "Mensagens automáticas de cuidados" },
      { icon: BarChart3, title: "Dashboard Visual", description: "Veja todos os pacientes em um funil" },
      { icon: Brain, title: "Sugestões de IA", description: "IA sugere próximos passos por paciente" },
    ],
    testimonial: { name: "Dra. Carla Mendes", role: "Dentista", company: "Clínica Sorriso", quote: "O robô confirma 90% das consultas automaticamente. Reduzi faltas em 60%!", avatar: "CM" },
    ctaText: "Quero Automatizar Minha Clínica",
    color: "cyan",
  },
  medico: {
    slug: "medico",
    title: "CRM para Médicos",
    subtitle: "Especializado para Clínicas Médicas",
    heroTitle: "Gestão de pacientes que",
    heroHighlight: "médicos merecem",
    heroDescription: "Automatize confirmações, retornos e acompanhamento de pacientes. IA que lê receitas, transcreve áudios e organiza tudo no prontuário do paciente.",
    painPoints: [
      "Pacientes que não confirmam consultas",
      "Dificuldade em acompanhar tratamentos longos",
      "Tempo perdido com ligações de confirmação",
      "Falta de histórico centralizado do paciente",
    ],
    benefits: [
      { icon: Stethoscope, title: "Prontuário Integrado", description: "Tudo do paciente em um só lugar" },
      { icon: Calendar, title: "Agenda Inteligente", description: "Confirmação automática de consultas" },
      { icon: Pill, title: "Leitura de Receitas", description: "IA lê fotos de receitas e organiza dados" },
      { icon: Heart, title: "Acompanhamento Contínuo", description: "Follow-up automático de tratamentos" },
      { icon: Bot, title: "Atendimento 24/7", description: "Robô tira dúvidas básicas dos pacientes" },
      { icon: BarChart3, title: "Métricas de Atendimento", description: "Veja performance da sua clínica" },
    ],
    testimonial: { name: "Dr. Ricardo Alves", role: "Cardiologista", company: "", quote: "O sistema lê as receitas que pacientes mandam e já organiza tudo. Economia de horas por semana.", avatar: "RA" },
    ctaText: "Modernizar Minha Clínica",
    color: "blue",
  },
  nutricionistas: {
    slug: "nutricionistas",
    title: "CRM para Nutricionistas",
    subtitle: "Especializado para Nutrição",
    heroTitle: "Acompanhe seus pacientes",
    heroHighlight: "de forma inteligente",
    heroDescription: "Gerencie dietas, envie lembretes automáticos e acompanhe a evolução dos seus pacientes. IA que responde dúvidas sobre alimentação 24/7.",
    painPoints: [
      "Pacientes que abandonam dietas no meio",
      "Dificuldade em fazer follow-up regular",
      "Muitas perguntas repetitivas sobre alimentação",
      "Falta de engajamento entre consultas",
    ],
    benefits: [
      { icon: ClipboardCheck, title: "Acompanhamento de Dietas", description: "Monitore evolução de cada paciente" },
      { icon: Bell, title: "Lembretes Motivacionais", description: "Mensagens automáticas de incentivo" },
      { icon: Bot, title: "FAQ Automático", description: "Robô responde dúvidas sobre alimentação" },
      { icon: Calendar, title: "Retornos Programados", description: "Avisos automáticos de consulta" },
      { icon: Target, title: "Metas e Resultados", description: "Acompanhe evolução visual" },
      { icon: MessageCircle, title: "Chat Direto", description: "Comunicação fácil com pacientes" },
    ],
    testimonial: { name: "Dra. Ana Beatriz", role: "Nutricionista", company: "", quote: "Meus pacientes se sentem acompanhados mesmo entre as consultas. A aderência às dietas melhorou muito!", avatar: "AB" },
    ctaText: "Engajar Meus Pacientes",
    color: "green",
  },
  influenciadores: {
    slug: "influenciadores",
    title: "CRM para Influenciadores",
    subtitle: "Gestão de Parcerias e Audiência",
    heroTitle: "Gerencie suas parcerias",
    heroHighlight: "como profissional",
    heroDescription: "Organize propostas de marcas, acompanhe campanhas e nunca perca uma oportunidade. Robô responde DMs automaticamente e qualifica parceiros.",
    painPoints: [
      "Propostas de marcas que se perdem nos DMs",
      "Dificuldade em acompanhar entregas de campanhas",
      "Muitos contatos sem organização",
      "Perder oportunidades por falta de resposta rápida",
    ],
    benefits: [
      { icon: Users, title: "Gestão de Parceiros", description: "Organize todas as marcas em um funil" },
      { icon: DollarSign, title: "Controle Financeiro", description: "Acompanhe pagamentos e comissões" },
      { icon: Bot, title: "Resposta Automática", description: "Robô responde DMs de propostas" },
      { icon: Calendar, title: "Calendário de Entregas", description: "Nunca perca prazo de campanha" },
      { icon: BarChart3, title: "Métricas de Campanhas", description: "Resultados de cada parceria" },
      { icon: MessageCircle, title: "Multi-Canais", description: "Gerencie Instagram, WhatsApp e mais" },
    ],
    testimonial: { name: "Juliana Costa", role: "Influenciadora", company: "500k seguidores", quote: "Antes perdia propostas nos DMs. Agora o robô responde e organiza tudo. Fechei 3x mais parcerias!", avatar: "JC" },
    ctaText: "Profissionalizar Minhas Parcerias",
    color: "pink",
  },
  advogado: {
    slug: "advogado",
    title: "CRM para Advogados",
    subtitle: "Especializado para Escritórios",
    heroTitle: "Gestão de clientes para",
    heroHighlight: "advogados modernos",
    heroDescription: "Organize seus processos, clientes e prazos. IA que responde dúvidas jurídicas básicas e qualifica novos clientes automaticamente.",
    painPoints: [
      "Clientes que ligam perguntando status do processo",
      "Dificuldade em acompanhar muitos casos",
      "Prazos processuais que podem ser perdidos",
      "Leads que entram mas não viram clientes",
    ],
    benefits: [
      { icon: Scale, title: "Gestão de Processos", description: "Cada caso organizado por etapa" },
      { icon: Bell, title: "Alertas de Prazo", description: "Nunca perca um prazo processual" },
      { icon: Bot, title: "FAQ Jurídico", description: "Robô responde dúvidas básicas" },
      { icon: ClipboardCheck, title: "Qualificação de Leads", description: "IA qualifica clientes potenciais" },
      { icon: MessageCircle, title: "Updates Automáticos", description: "Clientes informados sobre andamentos" },
      { icon: DollarSign, title: "Honorários", description: "Controle financeiro por cliente" },
    ],
    testimonial: { name: "Dr. Paulo Henrique", role: "Advogado", company: "PHM Advocacia", quote: "Clientes param de ligar perguntando do processo. O sistema avisa automaticamente!", avatar: "PH" },
    ctaText: "Modernizar Meu Escritório",
    color: "slate",
  },
  "donos-de-farmacias": {
    slug: "donos-de-farmacias",
    title: "CRM para Farmácias",
    subtitle: "Especializado para Drogarias",
    heroTitle: "Fidelize clientes da sua",
    heroHighlight: "farmácia automaticamente",
    heroDescription: "Gerencie medicamentos de uso contínuo, envie lembretes de recompra e crie relacionamento com seus clientes. IA que lê receitas e organiza pedidos.",
    painPoints: [
      "Clientes que esquecem de recomprar medicamentos",
      "Falta de relacionamento com clientes de uso contínuo",
      "Receitas que chegam por WhatsApp desorganizadas",
      "Perder vendas por falta de follow-up",
    ],
    benefits: [
      { icon: Pill, title: "Gestão de Uso Contínuo", description: "Acompanhe medicamentos de cada cliente" },
      { icon: Bell, title: "Lembrete de Recompra", description: "Avise quando o medicamento vai acabar" },
      { icon: Camera, title: "Leitura de Receitas", description: "IA lê fotos de receitas automaticamente" },
      { icon: Bot, title: "Atendimento 24/7", description: "Robô responde dúvidas básicas" },
      { icon: Users, title: "Programa de Fidelidade", description: "Gerencie pontos e benefícios" },
      { icon: BarChart3, title: "Relatórios de Vendas", description: "Métricas por cliente e produto" },
    ],
    testimonial: { name: "João Marcos", role: "Proprietário", company: "Farmácia Popular", quote: "O lembrete de recompra aumentou vendas de uso contínuo em 45%. Clientes adoram!", avatar: "JM" },
    ctaText: "Fidelizar Meus Clientes",
    color: "emerald",
  },
  infoprodutores: {
    slug: "infoprodutores",
    title: "CRM para Infoprodutores",
    subtitle: "Gestão de Alunos e Leads",
    heroTitle: "Venda mais cursos com",
    heroHighlight: "automação inteligente",
    heroDescription: "Gerencie leads, alunos e remarketing automaticamente. Robôs que vendem 24/7, qualificam interessados e reduzem cancelamentos.",
    painPoints: [
      "Leads que não viram alunos",
      "Alto índice de cancelamento/reembolso",
      "Dificuldade em fazer remarketing",
      "Alunos que não engajam no curso",
    ],
    benefits: [
      { icon: Target, title: "Funil de Vendas", description: "Visualize cada lead por etapa" },
      { icon: Bot, title: "Vendedor 24/7", description: "Robô apresenta e vende seu curso" },
      { icon: Heart, title: "Redução de Churn", description: "Follow-up automático com alunos" },
      { icon: Bell, title: "Remarketing Automático", description: "Reengaje leads que não compraram" },
      { icon: Users, title: "Gestão de Alunos", description: "Acompanhe progresso de cada um" },
      { icon: BarChart3, title: "Métricas de Conversão", description: "Veja o que funciona" },
    ],
    testimonial: { name: "Fernanda Lima", role: "Infoprodutora", company: "", quote: "O robô vendeu mais que minha equipe no lançamento! Conversão subiu 3x.", avatar: "FL" },
    ctaText: "Escalar Minhas Vendas",
    color: "purple",
  },
  "vendedores-de-nutraceuticos": {
    slug: "vendedores-de-nutraceuticos",
    title: "CRM para Nutraceuticos",
    subtitle: "Especializado para Suplementos",
    heroTitle: "Venda mais suplementos",
    heroHighlight: "com recompra automática",
    heroDescription: "Gerencie clientes, ciclos de recompra e follow-up automático. IA que explica produtos, tira dúvidas e sugere upgrades.",
    painPoints: [
      "Clientes que compram uma vez e somem",
      "Dificuldade em manter ciclo de recompra",
      "Muitas perguntas sobre produtos",
      "Falta de upsell/cross-sell organizado",
    ],
    benefits: [
      { icon: Pill, title: "Ciclo de Recompra", description: "Saiba quando cada cliente precisa repor" },
      { icon: Bell, title: "Lembrete Automático", description: "Avise antes do suplemento acabar" },
      { icon: Bot, title: "Consultor Virtual", description: "IA explica produtos e benefícios" },
      { icon: DollarSign, title: "Upsell Inteligente", description: "Sugestões de produtos complementares" },
      { icon: Target, title: "Funil de Vendas", description: "Acompanhe cada cliente" },
      { icon: Users, title: "Base de Clientes", description: "Histórico completo de compras" },
    ],
    testimonial: { name: "Carlos Eduardo", role: "Vendedor", company: "Nutra Premium", quote: "Recompra automática é game changer. Clientes recebem lembrete e já fazem pedido!", avatar: "CE" },
    ctaText: "Aumentar Minhas Recompras",
    color: "orange",
  },
  "donos-de-ecommerces": {
    slug: "donos-de-ecommerces",
    title: "CRM para E-commerce",
    subtitle: "Gestão de Clientes Online",
    heroTitle: "Transforme compradores em",
    heroHighlight: "clientes fiéis",
    heroDescription: "Gerencie pós-venda, recupere carrinhos abandonados e fidelize clientes. Integração com sua loja e robôs de atendimento 24/7.",
    painPoints: [
      "Carrinhos abandonados sem recuperação",
      "Clientes que compram uma vez e somem",
      "SAC por WhatsApp desorganizado",
      "Falta de relacionamento pós-venda",
    ],
    benefits: [
      { icon: ShoppingCart, title: "Recuperação de Carrinho", description: "Mensagens automáticas de abandono" },
      { icon: Package, title: "Tracking de Pedidos", description: "Cliente informado automaticamente" },
      { icon: Bot, title: "SAC Automatizado", description: "Robô responde dúvidas comuns" },
      { icon: Heart, title: "Programa de Fidelidade", description: "Recompensas automáticas" },
      { icon: Bell, title: "Recompra Inteligente", description: "Sugere produtos no momento certo" },
      { icon: BarChart3, title: "Analytics de Clientes", description: "Entenda comportamento de compra" },
    ],
    testimonial: { name: "Marina Santos", role: "Dona", company: "Loja Bella", quote: "Recuperamos 30% dos carrinhos abandonados. O robô responde clientes à noite quando dormimos!", avatar: "MS" },
    ctaText: "Fidelizar Meus Clientes",
    color: "indigo",
  },
  ferragens: {
    slug: "ferragens",
    title: "CRM para Ferragens",
    subtitle: "Gestão para Lojas de Materiais",
    heroTitle: "Gerencie clientes da sua",
    heroHighlight: "loja de ferragens",
    heroDescription: "Orçamentos organizados, follow-up de obras e atendimento automatizado. Nunca perca uma venda grande por falta de acompanhamento.",
    painPoints: [
      "Orçamentos que não viram vendas",
      "Clientes de obra que somem no meio",
      "Dificuldade em acompanhar projetos grandes",
      "Atendimento por WhatsApp desorganizado",
    ],
    benefits: [
      { icon: ClipboardCheck, title: "Gestão de Orçamentos", description: "Acompanhe cada proposta por etapa" },
      { icon: Building2, title: "Projetos de Obra", description: "Gerencie vendas de longo prazo" },
      { icon: Bot, title: "Atendimento 24/7", description: "Robô responde preços e disponibilidade" },
      { icon: Bell, title: "Follow-up de Orçamentos", description: "Lembrete automático para cliente" },
      { icon: Users, title: "Base de Clientes", description: "Histórico completo de compras" },
      { icon: Truck, title: "Gestão de Entregas", description: "Acompanhe entregas de materiais" },
    ],
    testimonial: { name: "Roberto Lima", role: "Proprietário", company: "Ferragens Central", quote: "O follow-up automático recuperou vários orçamentos que iam morrer. Vendas subiram 25%!", avatar: "RL" },
    ctaText: "Organizar Meus Orçamentos",
    color: "amber",
  },
  ecommerce: {
    slug: "ecommerce",
    title: "CRM para E-commerce",
    subtitle: "Gestão de Clientes Online",
    heroTitle: "Transforme sua loja em",
    heroHighlight: "máquina de vendas",
    heroDescription: "Recupere carrinhos, fidelize clientes e automatize seu SAC. Integração completa com sua loja online.",
    painPoints: [
      "Carrinhos abandonados todos os dias",
      "SAC que não dá conta da demanda",
      "Clientes que compram e nunca voltam",
      "Falta de relacionamento pós-venda",
    ],
    benefits: [
      { icon: ShoppingCart, title: "Recuperação de Carrinho", description: "Mensagens automáticas personalizadas" },
      { icon: Bot, title: "SAC Inteligente", description: "Robô resolve 80% das dúvidas" },
      { icon: Package, title: "Tracking Automático", description: "Cliente sabe onde está o pedido" },
      { icon: Heart, title: "Recompra Programada", description: "Sugere produtos no momento certo" },
      { icon: Users, title: "Segmentação", description: "Campanhas por perfil de cliente" },
      { icon: BarChart3, title: "Métricas de Retenção", description: "Veja lifetime value de clientes" },
    ],
    testimonial: { name: "Pedro Augusto", role: "CEO", company: "Shop Express", quote: "O robô atende 70% do SAC sozinho. Minha equipe foca em casos complexos.", avatar: "PA" },
    ctaText: "Escalar Meu E-commerce",
    color: "indigo",
  },
  "loja-de-moveis": {
    slug: "loja-de-moveis",
    title: "CRM para Móveis",
    subtitle: "Gestão para Lojas de Móveis",
    heroTitle: "Venda mais móveis com",
    heroHighlight: "follow-up inteligente",
    heroDescription: "Gerencie orçamentos de alto valor, acompanhe entregas e fidelize clientes. Perfeito para vendas consultivas.",
    painPoints: [
      "Orçamentos de móveis que não fecham",
      "Cliente some depois de ver preços",
      "Vendas de alto valor sem acompanhamento",
      "Entregas e montagens desorganizadas",
    ],
    benefits: [
      { icon: Home, title: "Projetos de Ambientes", description: "Organize vendas por cômodo/projeto" },
      { icon: ClipboardCheck, title: "Orçamentos Detalhados", description: "Acompanhe cada proposta" },
      { icon: Bell, title: "Follow-up Automático", description: "Não deixe cliente esfriar" },
      { icon: Truck, title: "Gestão de Entregas", description: "Tracking de entrega e montagem" },
      { icon: Bot, title: "Atendimento Virtual", description: "Robô mostra catálogo e preços" },
      { icon: Users, title: "Base de Clientes", description: "Histórico para recompra" },
    ],
    testimonial: { name: "Márcia Oliveira", role: "Gerente", company: "Móveis Elegance", quote: "Vendas de móveis são longas. O sistema mantém cliente aquecido até fechar!", avatar: "MO" },
    ctaText: "Fechar Mais Vendas",
    color: "rose",
  },
  empreiteiros: {
    slug: "empreiteiros",
    title: "CRM para Empreiteiros",
    subtitle: "Gestão de Obras e Clientes",
    heroTitle: "Gerencie suas obras e",
    heroHighlight: "clientes em um só lugar",
    heroDescription: "Orçamentos, acompanhamento de obras e comunicação com clientes. Tudo organizado do início ao fim do projeto.",
    painPoints: [
      "Orçamentos espalhados em vários lugares",
      "Cliente cobrando atualização de obra",
      "Dificuldade em acompanhar vários projetos",
      "Comunicação bagunçada com clientes",
    ],
    benefits: [
      { icon: Hammer, title: "Gestão de Obras", description: "Cada obra com suas etapas" },
      { icon: ClipboardCheck, title: "Orçamentos Organizados", description: "Do orçamento ao contrato" },
      { icon: Bell, title: "Updates Automáticos", description: "Cliente informado sobre progresso" },
      { icon: Camera, title: "Fotos de Obra", description: "Registre evolução visual" },
      { icon: DollarSign, title: "Controle Financeiro", description: "Pagamentos e custos por obra" },
      { icon: Bot, title: "Atendimento Virtual", description: "Robô responde dúvidas básicas" },
    ],
    testimonial: { name: "José Carlos", role: "Empreiteiro", company: "", quote: "Clientes pararam de ligar todo dia perguntando da obra. O sistema avisa automaticamente!", avatar: "JC" },
    ctaText: "Organizar Minhas Obras",
    color: "amber",
  },
};
